<div class="input-field">
	<label for="custom_field">Subscription</label>
	<select name="subscription_status" id="subscription_status">
		<option value="1">Yes</option>
		<option value="0">No</option>
	</select>
</div>
<div class="input-field">
	<label for="custom_field">Discount Type</label>
	<select name="discount_type" id="discount_type">
		<option value="1">Flat Rupees</option>
		<option value="0">Percentage</option>
	</select>
</div>
<div class="input-field">
	<label for="custom_field">Subscription Unit</label>
	<select name="subscription_unit" id="subscription_unit">
		<option value="d">Daily</option>
		<option value="w">Weekly</option>
		<option value="m">Monthly</option>
		<option value="y">Yearly</option>
		<option id="other" value="o">Other</option>
	</select>
</div>
<button id="test" onclick="test()">
Click
</button>