<?php 
if($this->subscrptionStatus($this->getProductid())){ ?>
<div id="div_subscription">
	<?php 
	
		$subscriptionDetail = $this->subscriptionDetail($this->getProductid()); ?>
	Subscrption:-
	<select>
		<option value="">Select for subscription</option>
		<?php  
			foreach ($subscriptionDetail as $key => $value) { ?>
				<option value=<?php echo $value; ?>> <?php echo $key; ?> - RS:-	<?php echo $value;?></option>
			<?php } ?>	
	</select>
</div>
<?php } ?>