<?php 
if($this->subscrptionStatus($this->getProductid()))
{ ?>
<div id="div_subscription">
<?php 
	$discountDetails = $this->discountDetail();
	if(!empty($discountDetails))
	{
		$disText = Thycart_Subscription_Block_Subscription::DISCOUNT_CONFIG;
		$currencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();
		$currency = Mage::app()->getLocale()->currency( $currencyCode )->getSymbol(); 
	?>
	Subscrption:-
	<select>
		<option value="">Select for subscription</option>
		<?php foreach($discountDetails as $detail) { 
			$disType = $detail['discount_type']; 
			$disVal = $detail['discount_value']; 
		?>
			<?php foreach($detail['available_units'] as $key=>$unit) { ?>
			<option value="<?php $key ?>"><?php echo $unit.' - '.$currency.$disVal.$disText[$disType]; ?> </option>
			<?php } 
		} 
		?>
	</select>
</div>
<?php 
	} 
} ?>