<?php 
if($this->subscrptionStatus($this->getProductid()))
{ ?>
<div id="div_subscription">
<?php 
	$discountDetails = $this->discountDetail();
	if(!empty($discountDetails))
	{
		$disText = Thycart_Subscription_Block_Subscription::DISCOUNT_CONFIG;
		$currencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();
		$currency = Mage::app()->getLocale()->currency($currencyCode)->getSymbol(); 
	?>
	Subscrption:-
	<select>
		<option value="">Select for subscription</option>
		<?php foreach($discountDetails as $detail) { ?>
			<?php foreach($detail['available_units'] as $key=>$unit) { ?>
			<option value="<?php echo $key ?>">
				<?php echo $unit.' - '.$currency.$detail['discount_value'].$disText[$detail['discount_type']]; ?>
			</option>
			<?php } 
		} ?>
	</select>
	<button id='subscription'>Subscribe Now</button>
</div>
<?php 
	} 
}
?>
<script type="text/javascript">
	jQuery('#subscription').click(function()
	{
		window.location.href="<?php echo Mage::getUrl('subscription/index/checkout'); ?>";
		return false;
	});
</script>